#!/usr/bin/env bash
# Generates .pipeline/repo-map.md — a compact, whole-territory map of every C# type
# under the repository (nested checkouts included — find does not respect
# .gitignore), grouped by directory. C# is the only mapped language; in a repo
# with no .cs files the map is just the header, and the planner leans on the
# scout and its read turns instead.
#
# Purpose: the fable-plan planner is a single-shot premium call; it cannot ask for a
# file it does not know exists. This map puts every type name (with base types) in
# front of it at ~30K tokens, so its bounded read turns are surgical, not speculative.
#
# Regeneration is cheap (<2s), so the script always regenerates — no staleness logic.
# Format notes:
#   - public AND internal types are included (internal seams matter for planning);
#     access/inheritance modifiers are stripped, base-type lists are kept.
#   - test directories (any path segment containing "Test") are collapsed to
#     comma-joined filenames — test type names mirror their filenames.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
mkdir -p .pipeline
OUT=.pipeline/repo-map.md

HEAD_REF=$(git rev-parse --verify --quiet HEAD || echo "no-commits")

{
  echo "# Repo type map (generated by fable-plan/repo-map.sh — do not edit)"
  echo "<!-- head: $HEAD_REF generated: $(date -u +%Y-%m-%dT%H:%M:%SZ) -->"
  echo "Legend: one line per file: 'File.cs: kind Name : BaseTypes; ...' (public+internal types,"
  echo "modifiers stripped). Test directories list filenames only. Files with no public/internal"
  echo "types are omitted."

  find . -name "*.cs" \
      -not -path "*/obj/*" -not -path "*/bin/*" -not -path "*/node_modules/*" 2>/dev/null \
    | sed 's|^\./||' | sort -u \
    | awk '
      function emit_tests() { if (testbuf != "") { print testbuf; testbuf = "" } }
      {
        f = $0
        n = split(f, p, "/"); dir = ""; for (i = 1; i < n; i++) dir = dir p[i] "/"
        file = p[n]
        buf = ""
        while ((getline line < f) > 0) {
          if (line !~ /^[[:space:]]*(public|internal)([[:space:]]+(static|sealed|abstract|partial|readonly|ref|unsafe|new))*[[:space:]]+(class|struct|interface|enum|record)([[:space:]]|<)/) continue
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
          gsub(/(public|internal|sealed|static|abstract|partial|readonly|unsafe) /, "", line)
          sub(/ where .*/, "", line)
          sub(/[[:space:]]*\{.*$/, "", line)
          sub(/;[[:space:]]*$/, "", line)
          buf = (buf == "" ? line : buf "; " line)
        }
        close(f)
        if (buf == "" && dir !~ /Test/) next
        if (dir != lastdir) { emit_tests(); printf "\n## %s\n", dir; lastdir = dir }
        if (dir ~ /Test/) {
          sub(/\.cs$/, "", file)
          testbuf = (testbuf == "" ? file : testbuf ", " file)
          if (length(testbuf) > 100) { print testbuf ","; testbuf = "" }
          next
        }
        print file ": " buf
      }
      END { emit_tests() }
    '
} > "$OUT"

echo "repo-map: $(wc -l < "$OUT" | tr -d ' ') lines, $(wc -c < "$OUT" | tr -d ' ') bytes -> $OUT"
